#!/usr/bin/env python3
"""Build and export XHS covers from style templates."""

from __future__ import annotations

import argparse
import html
import re
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate XHS cover HTML/PNG from templates in assets/covers."
    )
    parser.add_argument("--style", help="Style folder name under assets/covers (e.g. apple).")
    parser.add_argument(
        "--list-styles",
        action="store_true",
        help="List available styles and exit.",
    )
    parser.add_argument("--series-tag", default="Design Language · Demo")
    parser.add_argument("--author-name", default="Codex")
    parser.add_argument("--author-desc", default="Generated by xhs-cover-studio skill")
    parser.add_argument("--author-avatar", default="C")
    parser.add_argument("--overline", default="Design System Breakdown")
    parser.add_argument(
        "--headline",
        default="Turn one template\\ninto a brand-level\\nXHS cover",
        help="Use '\\n' for manual line breaks.",
    )
    parser.add_argument(
        "--subheadline",
        default="Choose a style, edit copy, and export a 1500x2000 cover in one command.",
    )
    parser.add_argument("--primary-cta", default="Get Template →")
    parser.add_argument("--secondary-cta", default="More Examples")
    parser.add_argument(
        "--feature",
        action="append",
        default=[],
        help="Repeatable. Format: 'Title|Description'. Use '\\n' for line breaks in description.",
    )
    parser.add_argument(
        "--tag",
        action="append",
        default=[],
        help="Repeatable. Replaces bottom tags from left to right.",
    )
    parser.add_argument(
        "--copy-text",
        default=None,
        help="Long copy. When set, script can auto-generate variants from this text.",
    )
    parser.add_argument(
        "--auto-variants",
        type=int,
        default=1,
        help="Number of outputs when using --copy-text (1-3).",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Output folder for generated files.",
    )
    parser.add_argument(
        "--filename-prefix",
        default=None,
        help="Filename prefix (default: <style>-cover).",
    )
    parser.add_argument(
        "--no-png",
        action="store_true",
        help="Only write HTML, skip PNG capture.",
    )
    return parser.parse_args()


def normalize_text(value: str) -> str:
    """Convert escaped newlines and escape HTML."""
    return html.escape(value.replace("\\n", "\n")).replace("\n", "<br>")


def replace_first(content: str, pattern: str, new_value: str) -> str:
    def repl(match: re.Match[str]) -> str:
        return f"{match.group(1)}{new_value}{match.group(3)}"

    updated, count = re.subn(pattern, repl, content, count=1, flags=re.S)
    if count == 0:
        raise ValueError(f"Pattern not found: {pattern}")
    return updated


def replace_many(content: str, pattern: str, values: list[str]) -> str:
    idx = 0

    def repl(match: re.Match[str]) -> str:
        nonlocal idx
        if idx >= len(values):
            return match.group(0)
        value = values[idx]
        idx += 1
        return f"{match.group(1)}{value}{match.group(3)}"

    return re.sub(pattern, repl, content, flags=re.S)


def list_styles(covers_dir: Path) -> int:
    styles = sorted(p.name for p in covers_dir.iterdir() if p.is_dir())
    if not styles:
        print("No styles found.", file=sys.stderr)
        return 1
    print("\n".join(styles))
    return 0


def parse_feature_pairs(raw_features: list[str]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for raw in raw_features:
        if "|" not in raw:
            raise ValueError(
                f"Invalid --feature value: {raw!r}. Expected format: 'Title|Description'."
            )
        title, desc = raw.split("|", 1)
        pairs.append((title, desc))
    return pairs


def split_copy_segments(text: str) -> list[str]:
    normalized = text.replace("\\n", "\n")
    parts = re.split(r"[\n\r。！？!?；;]+", normalized)
    cleaned = [re.sub(r"\s+", " ", p).strip(" 、,，") for p in parts]
    segments = [p for p in cleaned if p]
    if segments:
        return segments
    fallback = re.sub(r"\s+", " ", normalized).strip()
    return [fallback] if fallback else []


def has_cjk(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text))


def clip_text(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    if limit <= 1:
        return text[:limit]
    return text[: limit - 1].rstrip() + "…"


def line_limit_for(text: str) -> int:
    return 12 if has_cjk(text) else 26


def derive_variants_from_copy(copy_text: str, count: int) -> list[dict[str, object]]:
    segments = split_copy_segments(copy_text)
    if not segments:
        return []

    count = max(1, min(3, count))
    variants: list[dict[str, object]] = []

    for idx in range(count):
        base = idx * 4
        h1 = clip_text(segments[base % len(segments)], line_limit_for(segments[base % len(segments)]))
        h2 = clip_text(
            segments[(base + 1) % len(segments)],
            line_limit_for(segments[(base + 1) % len(segments)]),
        )
        h3 = clip_text(
            segments[(base + 2) % len(segments)],
            line_limit_for(segments[(base + 2) % len(segments)]),
        )
        headline = "\\n".join([h1, h2, h3])

        s1 = clip_text(segments[(base + 3) % len(segments)], 22 if has_cjk(copy_text) else 42)
        s2 = clip_text(segments[(base + 4) % len(segments)], 22 if has_cjk(copy_text) else 42)
        subheadline = f"{s1}｜{s2}"

        features: list[tuple[str, str]] = []
        for fidx in range(3):
            raw = segments[(base + 5 + fidx) % len(segments)]
            raw_next = segments[(base + 8 + fidx) % len(segments)]
            title_limit = 8 if has_cjk(raw) else 18
            desc_limit = 20 if has_cjk(raw_next) else 46
            title = clip_text(raw, title_limit)
            desc = clip_text(raw_next, desc_limit)
            features.append((title or f"Point {fidx + 1}", desc or "Key detail"))

        variants.append(
            {
                "headline": headline,
                "subheadline": subheadline,
                "features": features,
            }
        )

    return variants


def render_cover_html(
    template: str,
    *,
    series_tag: str,
    author_name: str,
    author_desc: str,
    author_avatar: str,
    overline: str,
    headline: str,
    subheadline: str,
    primary_cta: str,
    secondary_cta: str,
    feature_pairs: list[tuple[str, str]],
    tags: list[str],
) -> str:
    content = template
    replacements = [
        (r'(<span\s+class="series-tag">)(.*?)(</span>)', normalize_text(series_tag)),
        (r'(<span\s+class="author-name">)(.*?)(</span>)', normalize_text(author_name)),
        (r'(<span\s+class="author-desc">)(.*?)(</span>)', normalize_text(author_desc)),
        (r'(<div\s+class="author-avatar">)(.*?)(</div>)', normalize_text(author_avatar)),
        (r'(<div\s+class="overline">)(.*?)(</div>)', normalize_text(overline)),
        (r'(<h1\s+class="headline">)(.*?)(</h1>)', normalize_text(headline)),
        (r'(<p\s+class="subheadline">)(.*?)(</p>)', normalize_text(subheadline)),
        (r'(<button\s+class="cta-primary">)(.*?)(</button>)', normalize_text(primary_cta)),
        (
            r'(<button\s+class="cta-secondary">)(.*?)(</button>)',
            normalize_text(secondary_cta),
        ),
    ]
    for pattern, value in replacements:
        content = replace_first(content, pattern, value)

    if feature_pairs:
        content = replace_many(
            content,
            r'(<h3\s+class="feature-title">)(.*?)(</h3>)',
            [normalize_text(item[0]) for item in feature_pairs],
        )
        content = replace_many(
            content,
            r'(<p\s+class="feature-desc">)(.*?)(</p>)',
            [normalize_text(item[1]) for item in feature_pairs],
        )

    if tags:
        content = replace_many(
            content,
            r'(<span\s+class="tag(?: active)?">)(.*?)(</span>)',
            [normalize_text(t) for t in tags],
        )

    return content


def capture_png(skill_dir: Path, html_path: Path, png_path: Path) -> int:
    capture_script = skill_dir / "scripts" / "capture.sh"
    if not capture_script.exists():
        print(f"Missing capture script: {capture_script}", file=sys.stderr)
        return 1
    try:
        subprocess.run([str(capture_script), str(html_path), str(png_path)], check=True)
    except subprocess.CalledProcessError as exc:
        print(f"PNG export failed with exit code {exc.returncode}", file=sys.stderr)
        return exc.returncode
    return 0


def main() -> int:
    args = parse_args()
    skill_dir = Path(__file__).resolve().parents[1]
    covers_dir = skill_dir / "assets" / "covers"

    if args.list_styles:
        return list_styles(covers_dir)

    if not args.style:
        print("Error: --style is required unless --list-styles is used.", file=sys.stderr)
        return 2

    if args.auto_variants < 1 or args.auto_variants > 3:
        print("Error: --auto-variants must be between 1 and 3.", file=sys.stderr)
        return 2

    template_path = covers_dir / args.style / "template.html"
    if not template_path.exists():
        print(f"Style not found: {args.style}", file=sys.stderr)
        print("Run with --list-styles to see available style names.", file=sys.stderr)
        return 2

    try:
        base_feature_pairs = parse_feature_pairs(args.feature)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    template = template_path.read_text(encoding="utf-8")

    variants: list[dict[str, object]] = []
    if args.copy_text:
        variants = derive_variants_from_copy(args.copy_text, args.auto_variants)
        if not variants:
            print("Error: --copy-text did not produce valid content.", file=sys.stderr)
            return 2

    if not variants:
        variants = [
            {
                "headline": args.headline,
                "subheadline": args.subheadline,
                "features": base_feature_pairs,
            }
        ]

    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    prefix = args.filename_prefix or f"{args.style}-cover"

    total = len(variants)
    created_html: list[Path] = []
    created_png: list[Path] = []

    for idx, variant in enumerate(variants, start=1):
        variant_suffix = f"-v{idx}" if total > 1 else ""
        file_prefix = f"{prefix}{variant_suffix}"
        html_path = output_dir / f"{file_prefix}.html"
        png_path = output_dir / f"{file_prefix}.png"

        series_tag = args.series_tag
        if total > 1:
            series_tag = f"{series_tag} · {idx}/{total}"

        feature_pairs = variant.get("features") or base_feature_pairs
        content = render_cover_html(
            template,
            series_tag=series_tag,
            author_name=args.author_name,
            author_desc=args.author_desc,
            author_avatar=args.author_avatar,
            overline=args.overline,
            headline=str(variant.get("headline", args.headline)),
            subheadline=str(variant.get("subheadline", args.subheadline)),
            primary_cta=args.primary_cta,
            secondary_cta=args.secondary_cta,
            feature_pairs=list(feature_pairs),
            tags=args.tag,
        )

        html_path.write_text(content, encoding="utf-8")
        created_html.append(html_path)

        if not args.no_png:
            code = capture_png(skill_dir, html_path, png_path)
            if code != 0:
                return code
            created_png.append(png_path)

    for path in created_html:
        print(f"HTML: {path}")
    for path in created_png:
        print(f"PNG:  {path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
